

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: raul
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5430:5430"
    networks:
      - mired

volumes:
  postgres_data:

networks:
  mired:
    driver: bridge

